---
title: "Simple document"
output: html_document
---
```{r, echo = FALSE,message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
#library(janitor) 也可以使用 janitor::clean_names()后者不用将janitor包中的所有内容全部应用
```


## import dataset 'FAS_litters.csv'
Absolute Path: /Users/kaiyuhe/Desktop/data/Rdata/Import-data/data/FAS_litters.csv #only works on this computer
Relative Path: /data/FAS_litters.csv #
```{r}
setwd("/Users/kaiyuhe/Desktop/data/Rdata/Import-data") #don't do this often

litters_df = read_csv("data/FAS_litters.csv")
litters_df
```

```{r}
names(litters_df)

litters_df = janitor::clean_names(litters_df)
litters_df
```
```{r}
litters_df
#显示头几行和尾几行
head(litters_df)
tail(litters_df)
```
One jeff use a lot
```{r, eval = FALSE}
View(litters_df)
```

here's skimr
```{r}
skimr::skim(litters_df)
```

```{r, eval = FALSE}
help(read_csv)
litters_df = read_csv(
  "data/FAS_litters.csv",
  skip = 5,
  col_names = FALSE,
  na = "low"
                      )
View(litters_df)
```

## Parsing columns
```{r}
#设置每列数据的数据格式，read_csv 一般都会正确识别每一行数据的类型
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)
```
## import xlsx datas
```{r}
mlb11_df = read_excel("data/mlb11.xlsx")
mlb11_df
?read_excel
```

## 区块引用数据
```{r}
MLb_df = read_excel("data/LotR_Words.xlsx",range = "B3:D6")
MLb_df
```


## Read a SAS file
```{r, eval = FALSE}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
?read_sas
```

## Why never use read.csv?
```{r, eval = FALSE}
litters_df_base = read.csv("data/FAS_litters.csv")#import every thing and shows as a df 
litters_df = read_csv("data/FAS_litters.csv")
litters_df
```
```{r, eval = FALSE}
litters_df_base
```
## exporting data
a good way
```{r}
write_csv(MLb_df,"data/fellowship_words.csv")
```

